version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: reductive
    versions:
    - 0.6.0
  - dependency-name: approx
    versions:
    - 0.4.0
  - dependency-name: ndarray
    versions:
    - 0.14.0
  - dependency-name: rand
    versions:
    - 0.8.3
  - dependency-name: rand_xorshift
    versions:
    - 0.3.0
